version: "3.8"

services:
  doctorapp:
    container_name: doctorappcontainer
    build: .
    #   context: ..
    #   dockerfile: Dockerfile
    image: doctorapp:v2
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
